Improve the `loop_this` command to treat the kill sign. :)

diff --git a/bin/loop_this b/bin/loop_this
--- a/bin/loop_this
+++ b/bin/loop_this
@@ -1,13 +1,40 @@
 #!/usr/bin/env bash
+#
+# Public: Executes a given command in a given number of times.
+#
+# - size: number of times that the command will be executed.
+# - command: the command that will be executed.
+#
+# Modifiers:
+#
+# DONT_STOP: if this environment variable is set, the given
+# command will be execute in the given times, even if it does not
+# return success.
+#
+# Examples
+#
+#     # will execute the `ls` command 5 times.
+#     loop_this 5 ls
+#
+#     # will execute the `rspec` 10 times, even if the command return something
+#     # different from 0.
+#     DONT_STOP=1 loop_this 10 rspec
+###############################################################################
 
 params=($(echo "$@"))
-count=${params[0]}
 cmd=${params[@]:1}
+size=${params[0]}
+build_count=0
 error_count=0
 
-for ((i = 0; i < $count; ))
+report() {
+  echo -e "\n\nkilled: << Build $build_count (failed: $error_count) >>\n\n"
+  exit 1
+}; trap report SIGINT SIGTERM
+
+while [ $build_count -lt $size ]
 do
-  echo ">> Build $((++i)) (failed: $error_count)"
+  echo ">> Build $((++build_count)) (failed: $error_count)"
   echo ">> $cmd"
   $cmd
   if [[ $? != 0 ]]
@@ -21,4 +48,4 @@ do
   echo ""
 done
 
-echo -e "\nBuilds: $count\nErrors: $error_count\n"
+echo -e "\nBuilds: $size (failed: $error_count)\n"
